### ISSUE TITLE
Enable Cheats does not flip background

### ISSUE THREAD

**Issue by Eearslya** [TBartl/space-station-13-idle#236]
When cheats are enabled, a `reversed` class is applied to the content-wrapper to flip the background. However, the style specifies a background flip only if the `reversed` class is applied to the `background` div.

From `ContentWrapper.vue`:
```html
<template>
  <div class="content-wrapper" :class="{reversed: reversed}">
    <div class="background"></div>
    <component :is="'content-' + visibleSidebarItem" class="w-100 big-bottom-margin" />
  </div>
</template>
```
```css
.background.reversed {
  background-image: url("~@/assets/art/misc/background-alt-reversed.jpg");
}
```
